"use client";
import React, { useState, useContext } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { ThemeContext } from "./ThemeContext";

const Instruction = () => {
  const [currentInstruction, setCurrentInstruction] = useState(1);
  const route = useRouter();
  const { isDarkMode } = useContext(ThemeContext);

  const instructions = {
    1: {
      text: "Make sure to complete the whole process to earn full credit!",
      image: "/in1.svg", // Add the correct path to your SVG file
    },
    2: {
      text: "This program uses AI to create customized content just for you!",
      image: "/in2.svg",
    },
    3: {
      text: "If a link isn't working, kindly check the main path for guidance.",
      image: "/in3.svg",
    },
    4: {
      text: "The content in this module is generated by AI.",
      image: "/in4.svg",
    },
  };

  const handlePrevious = () => {
    setCurrentInstruction(currentInstruction - 1);
  };

  const handleNext = () => {
    setCurrentInstruction(currentInstruction + 1);
  };

  const Submitted = () => {
    route.push("/params/page?page=DepartmentJobRolls");
  };

  return (
    <div className="max-w-3xl mx-auto p-6 bg-white dark:bg-gray-800 rounded-lg shadow-md mt-10">
      <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-4">
        Welcome to CareerPilot AI
      </h1>
      
      <div className="prose dark:prose-invert">
        <p className="mb-4">
          This platform is designed to help you prepare for your career journey. Here are some instructions to get started:
        </p>

        <ul className="list-disc pl-6 mb-6 space-y-2">
          <li>Select a preparation module from the navigation</li>
          <li>Complete the assessments and exercises</li>
          <li>Review your feedback and improve your skills</li>
          <li>Practice regularly to enhance your performance</li>
          <li>Use the AI chatbot for any questions or guidance</li>
        </ul>
        
        <p>
          If you need any assistance, click the chat icon in the bottom right corner to speak with our AI assistant.
        </p>
      </div>
    </div>
  );
};

export default Instruction;
